name: TypeScript Action Test
description: TypeScript製のGitHub Actionテスト用アクション
author: toda.shunta

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: activity
  color: blue

# Define your inputs here.
inputs:
  name:
    description: 挨拶する名前
    required: false
    default: 'World'
  workflow-type:
    description:
      実行するワークフローのタイプ（hello-world または daily-activity）
    required: false
    default: 'hello-world'
  milliseconds:
    description: 待機時間（ミリ秒）
    required: false
    default: '1000'

# Define your outputs here.
outputs:
  message:
    description: Hello Worldワークフローからのメッセージ
  activity-summary:
    description: Daily Activityワークフローからのアクティビティサマリー
  time:
    description: メイン処理完了時刻

runs:
  using: node24
  main: dist/index.js
