name: Hello World Manual

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name to greet'
        required: false
        default: 'World'
        type: string

permissions:
  contents: read

jobs:
  hello-world:
    name: Hello World
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Hello World
        env:
          WORKFLOW_TYPE: hello-world
          INPUT_NAME: ${{ inputs.name }}
        run: node dist/index.js

      - name: Print Result
        run: echo "Hello World workflow completed!"
